# Generated by Django 5.0.14 on 2026-01-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='menucategory',
            new_name='menu_menuca_busines_e6a242_idx',
            old_name='menu_cat_bus_pos_idx',
        ),
        migrations.RenameIndex(
            model_name='menucategory',
            new_name='menu_menuca_busines_4b0b74_idx',
            old_name='menu_cat_bus_active_idx',
        ),
        migrations.RenameIndex(
            model_name='menuitem',
            new_name='menu_menuit_busines_4b8a5a_idx',
            old_name='menu_item_available_idx',
        ),
        migrations.RenameIndex(
            model_name='menuitem',
            new_name='menu_menuit_busines_95e160_idx',
            old_name='menu_item_category_idx',
        ),
        migrations.RenameIndex(
            model_name='menuitem',
            new_name='menu_menuit_busines_0ecdcc_idx',
            old_name='menu_item_featured_idx',
        ),
    ]
