# Generated by Django 5.0.14 on 2026-02-02 03:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_commercialsettings_options'),
        ('menu', '0002_rename_menu_cat_bus_pos_idx_menu_menuca_busines_e6a242_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicMenuConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('brand_name', models.CharField(max_length=120)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('theme_json', models.JSONField(blank=True, default=dict)),
                ('template_key', models.CharField(default='default_v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_menu_config', to='business.business')),
            ],
        ),
    ]
