# Generated by Django 5.0.14 on 2026-02-27 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menuengagementsettings_mercadopagoconnection_tiptransaction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tiptransaction',
            new_name='menu_tiptra_busines_dc0b84_idx',
            old_name='menu_tiptra_busines_idx',
        ),
        migrations.RenameIndex(
            model_name='tiptransaction',
            new_name='menu_tiptra_status_ad050b_idx',
            old_name='menu_tiptra_status_idx',
        ),
        migrations.RenameIndex(
            model_name='tiptransaction',
            new_name='menu_tiptra_externa_fa3a89_idx',
            old_name='menu_tiptra_ext_ref_idx',
        ),
    ]
