# Generated by Django 5.0.14 on 2026-03-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_menulayoutblock_menulayoutblockcategory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='menulayoutblock',
            new_name='menu_menula_busines_32faae_idx',
            old_name='menu_layout_business_position_idx',
        ),
        migrations.AlterField(
            model_name='menulayoutblockcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
