# Generated by Django 5.0.14 on 2026-04-21 00:20

import common.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_menucategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menubrandingsettings',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, storage=common.storages.public_media_storage, upload_to='menu/branding/logos/'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=common.storages.public_media_storage, upload_to='menu/categories/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=common.storages.public_media_storage, upload_to='menu/items/'),
        ),
    ]
