# Generated by Django 5.0.14 on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productcategory_product_category_and_more'),
        ('menu', '0012_menuitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='product_category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='menu_categories',
                to='catalog.productcategory',
            ),
        ),
    ]
