# Generated by Django 5.0.14 on 2026-01-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='default_service',
            field=models.CharField(choices=[('gestion', 'Gestion Comercial'), ('restaurante', 'Restaurantes')], default='gestion', max_length=32),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('plus', 'Plus')], default='starter', max_length=32),
        ),
    ]
