# Generated by Django 5.0.14 on 2026-01-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_commercialsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialsettings',
            options={'verbose_name': 'Commercial Settings', 'verbose_name_plural': 'Commercial Settings'},
        ),
    ]
