# Generated by Django 5.0.14 on 2026-02-03 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_commercialsettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='business.business'),
        ),
        migrations.AddField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('pending_activation', 'Pending Activation'), ('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=32),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_branches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_seats',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
