# Generated by Django 5.0.14 on 2026-02-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_subscription_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='default_service',
            field=models.CharField(choices=[('gestion', 'Gestion Comercial'), ('restaurante', 'Restaurantes'), ('menu_qr', 'Menú QR Online')], default='gestion', max_length=32),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('plus', 'Plus'), ('menu_qr', 'Menú QR')], default='starter', max_length=32),
        ),
    ]
