# Generated by Django 5.0.14 on 2026-02-17 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_create_profiles_for_existing_businesses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessbillingprofile',
            options={'verbose_name': 'Business Billing Profile', 'verbose_name_plural': 'Business Billing Profiles'},
        ),
        migrations.AlterModelOptions(
            name='businessbranding',
            options={'verbose_name': 'Business Branding', 'verbose_name_plural': 'Business Branding'},
        ),
        migrations.RemoveField(
            model_name='businessbillingprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='businessbillingprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='businessbillingprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='businessbillingprofile',
            name='legal_address',
        ),
        migrations.RemoveField(
            model_name='businessbillingprofile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='businessbillingprofile',
            name='state_province',
        ),
        migrations.RemoveField(
            model_name='businessbranding',
            name='id',
        ),
        migrations.AddField(
            model_name='businessbillingprofile',
            name='activity_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessbillingprofile',
            name='fiscal_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessbillingprofile',
            name='iibb',
            field=models.CharField(blank=True, help_text='Ingresos Brutos', max_length=64),
        ),
        migrations.AddField(
            model_name='businessbillingprofile',
            name='trade_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='businessbillingprofile',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='billing_profile', serialize=False, to='business.business'),
        ),
        migrations.AlterField(
            model_name='businessbillingprofile',
            name='commercial_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessbillingprofile',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='businessbillingprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='businessbillingprofile',
            name='tax_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='businessbillingprofile',
            name='tax_id_type',
            field=models.CharField(blank=True, choices=[('cuit', 'CUIT'), ('cuil', 'CUIL'), ('dni', 'DNI'), ('other', 'Otro')], max_length=16),
        ),
        migrations.AlterField(
            model_name='businessbillingprofile',
            name='vat_condition',
            field=models.CharField(blank=True, choices=[('responsable_inscripto', 'Responsable Inscripto'), ('monotributo', 'Monotributo'), ('exento', 'Exento'), ('consumidor_final', 'Consumidor Final'), ('no_responsable', 'No Responsable')], max_length=32),
        ),
        migrations.AlterField(
            model_name='businessbranding',
            name='accent_color',
            field=models.CharField(blank=True, help_text='Color hex (ej: #0066CC)', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessbranding',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='branding', serialize=False, to='business.business'),
        ),
        migrations.AlterField(
            model_name='businessbranding',
            name='logo_horizontal',
            field=models.ImageField(blank=True, help_text='Logo horizontal para encabezados de documentos', null=True, upload_to='business/logos/'),
        ),
        migrations.AlterField(
            model_name='businessbranding',
            name='logo_square',
            field=models.ImageField(blank=True, help_text='Logo cuadrado/icono', null=True, upload_to='business/logos/'),
        ),
        migrations.AlterModelTable(
            name='businessbillingprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='businessbranding',
            table=None,
        ),
    ]
