# Generated by Django 5.0.14 on 2026-02-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_migrate_legacy_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='default_service',
            field=models.CharField(choices=[('gestion', 'Gestion Comercial'), ('restaurante', 'Restaurantes'), ('menu_qr', 'Menú QR Online'), ('menu_qr_visual', 'Menú QR Visual'), ('menu_qr_marca', 'Menú QR Marca')], default='gestion', max_length=32),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('start', 'Start'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise'), ('menu_qr', 'Menú QR'), ('menu_qr_visual', 'Menú QR Visual'), ('menu_qr_marca', 'Menú QR Marca'), ('starter', 'Starter (Legacy)'), ('plus', 'Plus (Legacy)')], default='start', max_length=32),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='service',
            field=models.CharField(choices=[('gestion', 'Gestion Comercial'), ('restaurante', 'Restaurantes'), ('menu_qr', 'Menú QR Online'), ('menu_qr_visual', 'Menú QR Visual'), ('menu_qr_marca', 'Menú QR Marca')], default='gestion', max_length=32),
        ),
    ]
