# Generated by Django 5.0.14 on 2026-03-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_phase2a_business_slug_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('active', 'Active'), ('suspended', 'Suspended'), ('canceled', 'Canceled'), ('pending_activation', 'Pending Activation')], default='active', max_length=32),
        ),
    ]
