# Generated by Django 5.0.14 on 2026-03-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_business_status_add_trialing_past_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise'), ('menu_qr', 'Menú QR'), ('menu_qr_visual', 'Menú QR Visual'), ('menu_qr_marca', 'Menú QR Marca'), ('menu_qr_lite', 'Menú QR Lite'), ('menu_qr_pro', 'Menú QR Pro'), ('menu_qr_premium', 'Menú QR Premium'), ('start', 'Start (Legacy)'), ('plus', 'Plus (Legacy)')], default='starter', max_length=32),
        ),
    ]
