# Generated by Django 5.0.14 on 2026-04-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_expense_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='default_service',
            field=models.CharField(choices=[('gestion', 'Gestion Comercial'), ('restaurante', 'Restaurantes'), ('menu_qr', 'Menú QR Online'), ('menu_qr_visual', 'Menú QR Visual'), ('menu_qr_marca', 'Menú QR Marca'), ('qr_reviews', 'QR de Reseñas')], default='gestion', max_length=32),
        ),
        migrations.AlterField(
            model_name='business',
            name='service_type',
            field=models.CharField(blank=True, choices=[('gestion', 'Gestión Comercial'), ('restaurante', 'Restaurantes'), ('menu_qr', 'Menú QR'), ('menu_qr_visual', 'Menú QR Visual'), ('menu_qr_marca', 'Menú QR Marca'), ('qr_reviews', 'QR de Reseñas')], help_text='Canonical service type. Populated from default_service via data migration 0016.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise'), ('menu_qr', 'Menú QR'), ('menu_qr_visual', 'Menú QR Visual'), ('menu_qr_marca', 'Menú QR Marca'), ('menu_qr_lite', 'Menú QR Lite'), ('menu_qr_pro', 'Menú QR Pro'), ('menu_qr_premium', 'Menú QR Premium'), ('qr_reviews', 'QR de Reseñas'), ('start', 'Start (Legacy)'), ('plus', 'Plus (Legacy)')], default='starter', max_length=32),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='service',
            field=models.CharField(choices=[('gestion', 'Gestion Comercial'), ('restaurante', 'Restaurantes'), ('menu_qr', 'Menú QR Online'), ('menu_qr_visual', 'Menú QR Visual'), ('menu_qr_marca', 'Menú QR Marca'), ('qr_reviews', 'QR de Reseñas')], default='gestion', max_length=32),
        ),
    ]
