# Generated by Django 5.0.14 on 2026-04-21 00:20

import common.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_add_qr_reviews_plan_tiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessbranding',
            name='logo_horizontal',
            field=models.ImageField(blank=True, help_text='Logo horizontal para encabezados de documentos', null=True, storage=common.storages.public_media_storage, upload_to='business/logos/'),
        ),
        migrations.AlterField(
            model_name='businessbranding',
            name='logo_square',
            field=models.ImageField(blank=True, help_text='Logo cuadrado/icono', null=True, storage=common.storages.public_media_storage, upload_to='business/logos/'),
        ),
    ]
