# Generated by Django 5.0.14 on 2026-05-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_businessonboardingprogress'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='businessonboardingprogress',
            name='uq_onboarding_progress',
        ),
        migrations.AlterUniqueTogether(
            name='businessonboardingprogress',
            unique_together={('business', 'product_type', 'version')},
        ),
    ]
