# Generated by ChatGPT on 2026-01-19
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ('business', '0002_business_default_service_alter_subscription_plan'),
    ('catalog', '0001_initial'),
    ('customers', '0001_initial'),
  ]

  operations = [
    migrations.CreateModel(
      name='Sale',
      fields=[
        ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
        ('number', models.PositiveIntegerField()),
        ('status', models.CharField(choices=[('completed', 'Completada'), ('canceled', 'Cancelada')], default='completed', max_length=16)),
        ('note', models.TextField(blank=True)),
        ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('canceled_at', models.DateTimeField(blank=True, null=True)),
        ('business', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='sales', to='business.business')),
        ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='sales_canceled', to=settings.AUTH_USER_MODEL)),
        ('created_by', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='sales_created', to=settings.AUTH_USER_MODEL)),
        ('customer', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='sales', to='customers.customer')),
      ],
      options={
        'ordering': ['-created_at', '-number'],
      },
    ),
    migrations.CreateModel(
      name='SaleItem',
      fields=[
        ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
        ('name', models.CharField(max_length=255)),
        ('note', models.CharField(blank=True, max_length=255)),
        ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
        ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
        ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('product', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='sale_items', to='catalog.product')),
        ('sale', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='items', to='sales.sale')),
      ],
      options={
        'ordering': ['created_at'],
      },
    ),
    migrations.AddConstraint(
      model_name='sale',
      constraint=models.UniqueConstraint(fields=('business', 'number'), name='sales_business_number_unique'),
    ),
    migrations.AddIndex(
      model_name='sale',
      index=models.Index(fields=['business', 'status'], name='sale_business_status_idx'),
    ),
    migrations.AddIndex(
      model_name='sale',
      index=models.Index(fields=['business', 'created_at'], name='sale_business_created_idx'),
    ),
    migrations.AddIndex(
      model_name='saleitem',
      index=models.Index(fields=['sale'], name='saleitem_sale_idx'),
    ),
  ]
