# Generated by Django 5.0.14 on 2026-01-19 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='canceled_at',
            new_name='cancelled_at',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='total_amount',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='note',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='total_price',
            new_name='line_total',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='name',
            new_name='product_name_snapshot',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_sale_busines_1c85e6_idx',
            old_name='sale_business_status_idx',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_sale_busines_1e4819_idx',
            old_name='sale_business_created_idx',
        ),
        migrations.RenameIndex(
            model_name='saleitem',
            new_name='sales_salei_sale_id_413ea3_idx',
            old_name='saleitem_sale_idx',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='canceled_by',
            new_name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='note',
        ),
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta'), ('other', 'Otro')], default='cash', max_length=16),
        ),
        migrations.AddField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('completed', 'Completada'), ('cancelled', 'Cancelada')], default='completed', max_length=16),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'product'], name='sales_salei_sale_id_17278e_idx'),
        ),
    ]
