# Generated by Django 5.0.14 on 2026-01-19 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_customers_business_doc_number_idx_customers_c_busines_5cf7ba_idx_and_more'),
        ('sales', '0002_rename_canceled_at_sale_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer'),
        ),
    ]
