# Generated by Django 5.0.14 on 2026-02-17 15:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_business_default_service_and_more'),
        ('catalog', '0001_initial'),
        ('customers', '0004_rename_customers_business_doc_number_idx_customers_c_busines_5cf7ba_idx_and_more'),
        ('sales', '0004_sale_cash_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteSequence',
            fields=[
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='quote_sequence', serialize=False, to='business.business')),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'sales_quote_sequence',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviado'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('expired', 'Vencido'), ('converted', 'Convertido')], default='draft', max_length=16)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='business.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at', '-number'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_snapshot', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_line', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='catalog.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.quote')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['business', 'status'], name='sales_quote_busines_0adf2d_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['business', 'created_at'], name='sales_quote_busines_832ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['business', 'is_deleted'], name='sales_quote_busines_d604a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('business', 'number'), name='quotes_business_number_unique'),
        ),
        migrations.AddIndex(
            model_name='quoteitem',
            index=models.Index(fields=['quote'], name='sales_quote_quote_i_cc7d01_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteitem',
            index=models.Index(fields=['quote', 'product'], name='sales_quote_quote_i_239fbb_idx'),
        ),
    ]
