# Generated by Django 5.0.14 on 2026-03-13 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_business_status_add_trialing_past_due'),
        ('sales', '0007_order_orderhistory_orderitem_orderpayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSequence',
            fields=[
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='order_sequence', serialize=False, to='business.business')),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'sales_order_sequence',
            },
        ),
    ]
