# Generated by Django 5.0.14 on 2026-04-01 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_blogpo_status_c0e87f_idx',
            old_name='blog_blogpo_status_idx',
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_blogpo_created_2e77d7_idx',
            old_name='blog_blogpo_created_idx',
        ),
    ]
