# Generated by Django 5.0.14 on 2026-03-24 03:10

import apps.tax_backup.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0018_business_status_add_trialing_past_due'),
        ('treasury', '0005_expense_auto_source_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseFiscalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_type', models.CharField(choices=[('business', 'Negocio'), ('mixed', 'Mixto'), ('personal', 'Personal')], default='business', help_text='Destino del gasto: negocio, mixto o personal', max_length=20)),
                ('tax_status', models.CharField(choices=[('registrado', 'Registrado'), ('respaldado', 'Respaldado'), ('potencialmente_deducible', 'Potencialmente Deducible'), ('a_revisar', 'A Revisar'), ('no_respaldado_fiscalmente', 'No Respaldado Fiscalmente')], db_index=True, default='registrado', help_text='Estado fiscal calculado automáticamente por el rule engine', max_length=40)),
                ('amount_net', models.DecimalField(blank=True, decimal_places=4, help_text='Monto neto sin IVA', max_digits=19, null=True)),
                ('amount_vat', models.DecimalField(blank=True, decimal_places=4, help_text='IVA', max_digits=19, null=True)),
                ('is_capital_asset', models.BooleanField(default=False, help_text='Bien de uso / activo fijo — requiere revisión de amortización')),
                ('review_reason', models.TextField(blank=True, help_text='Motivo de revisión (generado por reglas o manual)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='Aislamiento multi-tenant', on_delete=django.db.models.deletion.CASCADE, related_name='expense_fiscal_profiles', to='business.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('expense', models.OneToOneField(help_text='Gasto de treasury asociado', on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_profile', to='treasury.expense')),
            ],
        ),
        migrations.CreateModel(
            name='DuplicateFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('provider_invoice_date_amount', 'Proveedor + Factura + Fecha + Monto'), ('exact_amount_date', 'Monto exacto + Fecha')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed_duplicate', 'Duplicado confirmado'), ('dismissed', 'Descartado')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fiscal_profile', models.ForeignKey(help_text='El gasto que dispara la sospecha', on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_flags', to='tax_backup.expensefiscalprofile')),
                ('matched_profile', models.ForeignKey(help_text='El gasto con el que coincide', on_delete=django.db.models.deletion.CASCADE, related_name='flagged_by', to='tax_backup.expensefiscalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExpensePaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta'), ('mercadopago', 'MercadoPago'), ('check', 'Cheque'), ('other', 'Otro')], max_length=20)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('reference', models.CharField(blank=True, help_text='Nro de transferencia, código de operación, etc.', max_length=255, null=True)),
                ('proof_file', models.FileField(blank=True, help_text='Comprobante de pago (transferencia, recibo, etc.)', null=True, upload_to=apps.tax_backup.models.payment_proof_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fiscal_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='tax_backup.expensefiscalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Imagen o PDF del comprobante (max 10 MB)', upload_to=apps.tax_backup.models.fiscal_document_upload_path)),
                ('document_type', models.CharField(choices=[('factura', 'Factura'), ('recibo', 'Recibo'), ('ticket', 'Ticket'), ('nota_credito', 'Nota de Crédito'), ('nota_debito', 'Nota de Débito'), ('otro', 'Otro')], default='factura', max_length=20)),
                ('issuer_name', models.CharField(blank=True, help_text='Razón social del emisor', max_length=255, null=True)),
                ('issuer_tax_id', models.CharField(blank=True, help_text='CUIT / RFC del emisor', max_length=50, null=True)),
                ('buyer_name', models.CharField(blank=True, help_text='Razón social del comprador', max_length=255, null=True)),
                ('buyer_tax_id', models.CharField(blank=True, help_text='CUIT / RFC del comprador', max_length=50, null=True)),
                ('point_of_sale', models.CharField(blank=True, help_text='Punto de venta (ej: 0001)', max_length=10, null=True)),
                ('invoice_number', models.CharField(blank=True, help_text='Número de comprobante', max_length=50, null=True)),
                ('issue_date', models.DateField(blank=True, help_text='Fecha de emisión', null=True)),
                ('currency', models.CharField(default='ARS', max_length=10)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('vat', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('is_fiscal_document', models.BooleanField(default=False, help_text='True si es un comprobante fiscal válido (factura tipo A/B/C, etc.)')),
                ('parse_status', models.CharField(choices=[('manual', 'Ingreso manual'), ('pending', 'Pendiente de extracción'), ('parsed', 'Datos extraídos'), ('failed', 'Extracción fallida')], default='manual', help_text='Estado de extracción automática de datos (OCR futuro)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fiscal_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tax_backup.expensefiscalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringServiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(help_text='Razón social o nombre del proveedor', max_length=255)),
                ('provider_tax_id', models.CharField(blank=True, help_text='CUIT / RFC / RUT del proveedor', max_length=50, null=True)),
                ('needs_monthly_invoice', models.BooleanField(default=False, help_text='¿Requiere comprobante fiscal por cada período?')),
                ('expected_document_type', models.CharField(choices=[('factura', 'Factura'), ('recibo', 'Recibo'), ('ticket', 'Ticket'), ('nota_credito', 'Nota de Crédito'), ('nota_debito', 'Nota de Débito'), ('otro', 'Otro')], default='factura', help_text='Tipo de comprobante esperado cada período', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_service_profiles', to='business.business')),
                ('fixed_expense', models.OneToOneField(help_text='Gasto fijo / servicio recurrente asociado', on_delete=django.db.models.deletion.CASCADE, related_name='service_profile', to='treasury.fixedexpense')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePeriodAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('missing_invoice', 'Comprobante faltante'), ('incomplete_data', 'Datos incompletos')], max_length=30)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('resolved', 'Resuelta'), ('dismissed', 'Descartada')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixed_expense_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_backup_alerts', to='treasury.fixedexpenseperiod')),
                ('service_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_alerts', to='tax_backup.recurringserviceprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TaxStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('registrado', 'Registrado'), ('respaldado', 'Respaldado'), ('potencialmente_deducible', 'Potencialmente Deducible'), ('a_revisar', 'A Revisar'), ('no_respaldado_fiscalmente', 'No Respaldado Fiscalmente')], help_text='Null para el primer estado asignado', max_length=40, null=True)),
                ('new_status', models.CharField(choices=[('registrado', 'Registrado'), ('respaldado', 'Respaldado'), ('potencialmente_deducible', 'Potencialmente Deducible'), ('a_revisar', 'A Revisar'), ('no_respaldado_fiscalmente', 'No Respaldado Fiscalmente')], max_length=40)),
                ('rule_code', models.CharField(help_text='Código de la regla que disparó el cambio (ej: RULE_NO_FISCAL_DOC)', max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fiscal_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='tax_backup.expensefiscalprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='expensefiscalprofile',
            index=models.Index(fields=['business', 'tax_status'], name='tb_fp_biz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='expensefiscalprofile',
            index=models.Index(fields=['business', 'allocation_type'], name='tb_fp_biz_alloc_idx'),
        ),
        migrations.AddIndex(
            model_name='expensefiscalprofile',
            index=models.Index(fields=['business', 'created_at'], name='tb_fp_biz_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='expensefiscalprofile',
            constraint=models.UniqueConstraint(fields=('expense',), name='tb_one_fiscal_profile_per_expense'),
        ),
        migrations.AddIndex(
            model_name='duplicateflag',
            index=models.Index(fields=['fiscal_profile', 'status'], name='tb_dup_profile_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='duplicateflag',
            constraint=models.UniqueConstraint(fields=('fiscal_profile', 'matched_profile'), name='tb_unique_duplicate_pair'),
        ),
        migrations.AddIndex(
            model_name='expensepaymentdetail',
            index=models.Index(fields=['fiscal_profile'], name='tb_pay_profile_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['fiscal_profile'], name='tb_doc_profile_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['issuer_tax_id', 'invoice_number', 'issue_date', 'total'], name='tb_doc_dup_detect_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringserviceprofile',
            index=models.Index(fields=['business'], name='tb_rsp_biz_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringserviceprofile',
            constraint=models.UniqueConstraint(fields=('fixed_expense',), name='tb_one_service_profile_per_fixed'),
        ),
        migrations.AddIndex(
            model_name='serviceperiodalert',
            index=models.Index(fields=['service_profile', 'status'], name='tb_alert_svc_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceperiodalert',
            constraint=models.UniqueConstraint(fields=('service_profile', 'fixed_expense_period', 'alert_type'), name='tb_one_alert_per_period_type'),
        ),
        migrations.AddIndex(
            model_name='taxstatuslog',
            index=models.Index(fields=['fiscal_profile', '-created_at'], name='tb_log_profile_date_idx'),
        ),
    ]
