# Generated by Django 5.0.14 on 2026-03-24 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_backup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicateflag',
            name='fiscal_profile',
            field=models.ForeignKey(help_text='Perfil con ID menor del par', on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_flags', to='tax_backup.expensefiscalprofile'),
        ),
        migrations.AlterField(
            model_name='duplicateflag',
            name='matched_profile',
            field=models.ForeignKey(help_text='Perfil con ID mayor del par', on_delete=django.db.models.deletion.CASCADE, related_name='flagged_by', to='tax_backup.expensefiscalprofile'),
        ),
        migrations.AddConstraint(
            model_name='duplicateflag',
            constraint=models.CheckConstraint(check=models.Q(('fiscal_profile', models.F('matched_profile')), _negated=True), name='tb_dup_no_self_ref'),
        ),
    ]
