# Generated by Django 5.0.14 on 2026-03-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_backup', '0005_fiscaldocument_processing_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscaldocument',
            name='document_subtype',
            field=models.CharField(blank=True, help_text='Subtipo AFIP original (ej: Factura A, Nota de Crédito B)', max_length=80, null=True),
        ),
    ]
