# Generated by Django 5.0.14 on 2026-03-09 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0006_cashsession_opened_by_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashsession',
            name='terminal',
            field=models.ForeignKey(blank=True, help_text='Phase 2A canonical terminal reference. Coexists with legacy `register`.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_sessions', to='cash.terminal'),
        ),
        migrations.AlterField(
            model_name='operatorsession',
            name='total_orders',
            field=models.PositiveIntegerField(default=0, help_text='Cached count of orders processed in this session.'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='cash_register',
            field=models.OneToOneField(blank=True, help_text='Transition reference: linked CashRegister. Null for post-Phase-2A terminals.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal', to='cash.cashregister'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='config',
            field=models.JSONField(blank=True, help_text='Terminal-specific config: default_printer, sector, etc.', null=True),
        ),
    ]
