# Generated by Django 5.0.14 on 2026-01-24 10:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0004_alter_commercialsettings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resto_tables', to='business.business')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TableLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grid_cols', models.PositiveIntegerField(default=12)),
                ('grid_rows', models.PositiveIntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resto_table_layout', to='business.business')),
            ],
            options={
                'ordering': ['business'],
            },
        ),
        migrations.CreateModel(
            name='TablePlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('w', models.PositiveIntegerField(default=1)),
                ('h', models.PositiveIntegerField(default=1)),
                ('rotation', models.IntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resto_table_placements', to='business.business')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='resto.tablelayout')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='resto.table')),
            ],
            options={
                'ordering': ['table__code'],
            },
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['business', 'is_enabled'], name='resto_table_busines_4474e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('business', 'code'), name='resto_table_unique_code_per_business'),
        ),
        migrations.AddIndex(
            model_name='tableplacement',
            index=models.Index(fields=['business', 'table'], name='resto_table_busines_60f78c_idx'),
        ),
        migrations.AddIndex(
            model_name='tableplacement',
            index=models.Index(fields=['layout'], name='resto_table_layout__5e8e54_idx'),
        ),
        migrations.AddConstraint(
            model_name='tableplacement',
            constraint=models.UniqueConstraint(fields=('layout', 'table'), name='resto_tableplacement_unique_layout_table'),
        ),
    ]
