# Generated by Django 5.0.14 on 2026-01-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='area',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='table',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='table',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['business', 'is_paused'], name='resto_table_busines_80c1f8_idx'),
        ),
        migrations.AddField(
            model_name='tableplacement',
            name='z_index',
            field=models.IntegerField(default=0),
        ),
    ]
