# Generated by Django 5.0.14 on 2026-01-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0002_table_state_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='table',
            new_name='resto_table_busines_84f759_idx',
            old_name='resto_table_busines_80c1f8_idx',
        ),
    ]
