# Generated by ChatGPT on 2026-01-19
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    ('business', '0002_business_default_service_alter_subscription_plan'),
  ]

  operations = [
    migrations.CreateModel(
      name='Customer',
      fields=[
        ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
        ('name', models.CharField(max_length=255)),
        ('email', models.EmailField(max_length=254, blank=True)),
        ('phone', models.CharField(max_length=64, blank=True)),
        ('tax_id', models.CharField(max_length=64, blank=True)),
        ('note', models.TextField(blank=True)),
        ('tags', models.JSONField(default=list, blank=True)),
        ('is_active', models.BooleanField(default=True)),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('business', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='customers', to='business.business')),
      ],
      options={
        'ordering': ['name'],
      },
    ),
    migrations.AddIndex(
      model_name='customer',
      index=models.Index(fields=['business', 'name'], name='customers_biz_name_idx'),
    ),
    migrations.AddIndex(
      model_name='customer',
      index=models.Index(fields=['business', 'email'], name='customers_biz_email_idx'),
    ),
    migrations.AddIndex(
      model_name='customer',
      index=models.Index(fields=['business', 'phone'], name='customers_biz_phone_idx'),
    ),
  ]
