# Generated by Django 5.0.14 on 2026-01-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_busines_67b0d8_idx',
            old_name='customers_biz_name_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_busines_13d809_idx',
            old_name='customers_biz_email_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_busines_fc2d10_idx',
            old_name='customers_biz_phone_idx',
        ),
    ]
