# Generated by ChatGPT on 2026-01-19
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_customers_biz_name_idx_customers_c_busines_67b0d8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.CharField(
                choices=[('individual', 'Persona'), ('company', 'Empresa')],
                default='individual',
                max_length=16,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='doc_type',
            field=models.CharField(
                blank=True,
                choices=[('dni', 'DNI'), ('cuit', 'CUIT'), ('passport', 'Pasaporte'), ('other', 'Otro')],
                default='',
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='doc_number',
            field=models.CharField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_condition',
            field=models.CharField(
                blank=True,
                choices=[
                    ('consumer', 'Consumidor Final'),
                    ('registered', 'Responsable Inscripto'),
                    ('monotax', 'Monotributo'),
                    ('exempt', 'Exento'),
                    ('other', 'Otro'),
                ],
                default='',
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='address_line',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='province',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tax_id',
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business', 'doc_number'], name='customers_business_doc_number_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(
                condition=Q(doc_type__gt='') & Q(doc_number__gt=''),
                fields=('business', 'doc_type', 'doc_number'),
                name='customer_unique_document_per_business',
            ),
        ),
    ]
