# Generated by Django 5.0.14 on 2026-01-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_extended_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_busines_5cf7ba_idx',
            old_name='customers_business_doc_number_idx',
        ),
        migrations.AlterField(
            model_name='customer',
            name='doc_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='customer',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('dni', 'DNI'), ('cuit', 'CUIT'), ('passport', 'Pasaporte'), ('other', 'Otro')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_condition',
            field=models.CharField(blank=True, choices=[('consumer', 'Consumidor Final'), ('registered', 'Responsable Inscripto'), ('monotax', 'Monotributo'), ('exempt', 'Exento'), ('other', 'Otro')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('individual', 'Persona'), ('company', 'Empresa')], default='individual', max_length=16),
        ),
    ]
