# Generated by Django 5.0.14 on 2026-04-03 19:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0020_add_qr_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('google_place_id', models.CharField(blank=True, default='', max_length=255)),
                ('google_review_url', models.URLField(blank=True, default='')),
                ('custom_redirect_url', models.URLField(blank=True, default='')),
                ('redirect_threshold', models.PositiveSmallIntegerField(default=4, help_text='Ratings >= this value trigger external redirect instead of internal feedback.')),
                ('collect_contact', models.BooleanField(default=False)),
                ('thank_you_message', models.CharField(blank=True, default='¡Gracias por tu opinión!', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_config', to='business.business')),
            ],
            options={
                'verbose_name': 'Review Config',
                'verbose_name_plural': 'Review Configs',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('contact_info', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(choices=[('qr', 'QR Code'), ('menu', 'Carta Online'), ('direct', 'Link directo')], default='qr', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('reviewed', 'Revisado'), ('archived', 'Archivado')], default='pending', max_length=16)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='business.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', '-created_at'], name='reviews_rev_busines_02bd4d_idx'), models.Index(fields=['business', 'status'], name='reviews_rev_busines_d642f9_idx'), models.Index(fields=['business', 'rating'], name='reviews_rev_busines_a77d19_idx')],
            },
        ),
    ]
