# Generated by Django 5.0.14 on 2026-04-03 19:52

from django.db import migrations


def forward(apps, schema_editor):
    """Copy reviews data from MenuEngagementSettings to ReviewConfig."""
    MenuEngagementSettings = apps.get_model('menu', 'MenuEngagementSettings')
    ReviewConfig = apps.get_model('reviews', 'ReviewConfig')

    for eng in MenuEngagementSettings.objects.all():
        has_reviews_data = (
            eng.reviews_enabled
            or eng.google_place_id
            or eng.google_review_url
        )
        if not has_reviews_data:
            continue

        ReviewConfig.objects.get_or_create(
            business=eng.business,
            defaults={
                'enabled': eng.reviews_enabled,
                'google_place_id': eng.google_place_id or '',
                'google_review_url': eng.google_review_url or '',
            },
        )


def backward(apps, schema_editor):
    """No-op: legacy fields are still intact."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('menu', '0009_rename_menu_layout_business_position_idx_menu_menula_busines_32faae_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
