# Generated by Django 5.0.14 on 2026-04-09 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_reviewvisit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reviewvisit',
            new_name='reviews_rev_busines_0f8ecf_idx',
            old_name='reviews_rev_busines_idx_visit',
        ),
    ]
