# Generated by Django 5.0.14 on 2026-04-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_rename_reviews_rev_busines_idx_visit_reviews_rev_busines_0f8ecf_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewconfig',
            name='mode',
            field=models.CharField(choices=[('direct', 'Directo'), ('smart_filter', 'Filtro inteligente')], default='direct', help_text='direct = all reviews redirect to Google; smart_filter = route by rating.', max_length=16),
        ),
        migrations.AddField(
            model_name='reviewconfig',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='When the smart-filter trial expires. NULL = no trial started.', null=True),
        ),
        migrations.AddField(
            model_name='reviewconfig',
            name='trial_used',
            field=models.BooleanField(default=False, help_text='True once the 7-day smart-filter trial has been consumed.'),
        ),
    ]
