# Generated by Django 5.0.14 on 2026-04-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_add_qr_reviews_plan_tiers'),
        ('reviews', '0008_add_google_place_snapshot_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewvisit',
            name='ip_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='reviewconfig',
            name='google_place_formatted_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='reviewconfig',
            name='google_place_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='reviewconfig',
            name='google_place_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='reviewvisit',
            index=models.Index(fields=['business', 'ip_hash', '-created_at'], name='reviewvisit_biz_ip_created'),
        ),
    ]
