# Generated by Django 5.0.14 on 2026-05-16 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_reviewqrposterdesign'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reviewqrposterdesign',
            new_name='reviews_rev_busines_17b16d_idx',
            old_name='reviews_rev_busines_updated_idx',
        ),
    ]
