# Generated by Django 5.0.14 on 2026-01-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager / Encargado'), ('cashier', 'Cashier / Caja'), ('staff', 'Staff / Empleado'), ('viewer', 'Solo lectura'), ('kitchen', 'Cocina'), ('salon', 'Salon / Toma pedidos'), ('analyst', 'Analyst')], default='owner', max_length=24),
        ),
    ]
