# Generated by Django 5.0.14 on 2026-02-12 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accessauditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accessauditlog',
            new_name='accounts_ac_busines_cb7852_idx',
            old_name='accounts_ac_busines_idx',
        ),
        migrations.RenameIndex(
            model_name='accessauditlog',
            new_name='accounts_ac_target__98f6dd_idx',
            old_name='accounts_ac_target__idx',
        ),
    ]
