# Generated by Django 5.0.14 on 2026-02-13 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_accounts_ac_busines_idx_accounts_ac_busines_cb7852_idx_and_more'),
        ('business', '0007_alter_business_default_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager / Encargado'), ('cashier', 'Cashier / Caja'), ('staff', 'Staff / Empleado'), ('viewer', 'Solo lectura'), ('kitchen', 'Cocina'), ('salon', 'Salon / Toma pedidos'), ('analyst', 'Analyst')], help_text='Role to configure (e.g., manager, cashier)', max_length=24)),
                ('service', models.CharField(help_text='Service context (gestion, restaurante, menu_qr)', max_length=24)),
                ('permission', models.CharField(help_text='Permission key (e.g., view_sales, manage_products)', max_length=64)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this permission is enabled for the role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permission_overrides', to='business.business')),
            ],
            options={
                'indexes': [models.Index(fields=['business', 'service', 'role'], name='accounts_ro_busines_b31d64_idx')],
                'unique_together': {('business', 'role', 'service', 'permission')},
            },
        ),
    ]
