# Generated by Django 5.0.14 on 2026-02-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rolepermissionoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessauditlog',
            name='action',
            field=models.CharField(choices=[('PASSWORD_RESET', 'Password Reset'), ('PIN_ROTATED', 'PIN Rotated'), ('ACCOUNT_DISABLED', 'Account Disabled'), ('ACCOUNT_ENABLED', 'Account Enabled'), ('ROLE_CHANGED', 'Role Changed'), ('ROLE_PERMISSIONS_UPDATED', 'Role Permissions Updated'), ('SESSIONS_REVOKED', 'Sessions Revoked'), ('MEMBERSHIP_CREATED', 'Membership Created'), ('MEMBERSHIP_DELETED', 'Membership Deleted')], max_length=32),
        ),
    ]
