# Generated by Django 5.0.14 on 2026-03-09 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_accessauditlog_target_user_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessauditlog',
            name='action',
            field=models.CharField(choices=[('MEMBERSHIP_CREATED', 'Membership Created'), ('MEMBERSHIP_UPDATED', 'Membership Updated'), ('MEMBERSHIP_DELETED', 'Membership Deleted'), ('MEMBERSHIP_SUSPENDED', 'Membership Suspended'), ('PASSWORD_RESET', 'Password Reset'), ('PASSWORD_RESET_CONFIRMED', 'Password Reset Confirmed'), ('EMAIL_VERIFICATION_SENT', 'Email Verification Sent'), ('EMAIL_VERIFIED', 'Email Verified'), ('EMPLOYEE_CREATED', 'Employee Created'), ('EMPLOYEE_UPDATED', 'Employee Updated'), ('EMPLOYEE_SUSPENDED', 'Employee Suspended'), ('EMPLOYEE_REACTIVATED', 'Employee Reactivated'), ('EMPLOYEE_DELETED', 'Employee Deleted'), ('PIN_RESET', 'PIN Reset'), ('PIN_CHANGED', 'PIN Changed'), ('PIN_ROTATED', 'PIN Rotated'), ('ROLE_CHANGED', 'Role Changed'), ('PERMISSION_OVERRIDE_SET', 'Permission Override Set'), ('ROLE_PERMISSIONS_UPDATED', 'Role Permissions Updated'), ('CASH_SESSION_OPENED', 'Cash Session Opened'), ('CASH_SESSION_CLOSED', 'Cash Session Closed'), ('CASH_SESSION_FORCE_CLOSED', 'Cash Session Force Closed'), ('CASH_MOVEMENT_CREATED', 'Cash Movement Created'), ('OPERATOR_SESSION_STARTED', 'Operator Session Started'), ('OPERATOR_SESSION_ENDED', 'Operator Session Ended'), ('SALE_CREATED_POS', 'Sale Created (POS)'), ('SUBSCRIPTION_CREATED', 'Subscription Created'), ('SUBSCRIPTION_STATUS_CHANGED', 'Subscription Status Changed'), ('SUBSCRIPTION_CANCELED', 'Subscription Canceled'), ('TRIAL_STARTED', 'Trial Started'), ('TRIAL_EXPIRED', 'Trial Expired'), ('SESSION_REVOKED', 'Session Revoked'), ('SESSIONS_REVOKED', 'Sessions Revoked'), ('LOGIN_FAILED', 'Login Failed'), ('ACCESS_DENIED', 'Access Denied'), ('ACCOUNT_DISABLED', 'Account Disabled'), ('ACCOUNT_ENABLED', 'Account Enabled')], max_length=32),
        ),
        migrations.AlterField(
            model_name='accessauditlog',
            name='actor_employee',
            field=models.ForeignKey(blank=True, help_text='Set when actor_type=EMPLOYEE.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions_performed', to='accounts.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='accessauditlog',
            name='actor_type',
            field=models.CharField(choices=[('USER', 'Usuario Admin'), ('EMPLOYEE', 'Empleado Operativo'), ('SYSTEM', 'Sistema / Tarea Automatizada')], default='USER', help_text='USER for admin actions; EMPLOYEE for POS actions; SYSTEM for automated tasks.', max_length=16),
        ),
        migrations.AlterField(
            model_name='accessauditlog',
            name='after_json',
            field=models.JSONField(blank=True, help_text='State of the object after the action.', null=True),
        ),
        migrations.AlterField(
            model_name='accessauditlog',
            name='before_json',
            field=models.JSONField(blank=True, help_text='State of the object before the action.', null=True),
        ),
        migrations.AlterField(
            model_name='accessauditlog',
            name='entity_type',
            field=models.CharField(blank=True, default='', help_text='Model name of affected object. e.g. membership, employee_profile, cash_session.', max_length=64),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='must_change_pin',
            field=models.BooleanField(default=False, help_text='If True, employee must change PIN on next POS login.'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='permission_overrides',
            field=models.JSONField(blank=True, help_text='Per-employee overrides over role_type defaults.', null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='permissions',
            field=models.JSONField(blank=True, help_text='Per-user permission overrides. e.g. {"can_void_order": true}', null=True),
        ),
    ]
