# Generated by Django 5.0.14 on 2026-03-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_accessauditlog_onboarding_checkout_started'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountprofile',
            options={},
        ),
    ]
