# Generated by Django 5.0.14 on 2026-03-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_support_tickets_phase3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessauditlog',
            name='action',
            field=models.CharField(choices=[('MEMBERSHIP_CREATED', 'Membership Created'), ('MEMBERSHIP_UPDATED', 'Membership Updated'), ('MEMBERSHIP_DELETED', 'Membership Deleted'), ('MEMBERSHIP_SUSPENDED', 'Membership Suspended'), ('MEMBER_REACTIVATED', 'Member Reactivated'), ('MEMBER_REMOVED', 'Member Removed'), ('USER_CREATED', 'Internal User Created'), ('PASSWORD_RESET', 'Password Reset'), ('PASSWORD_RESET_CONFIRMED', 'Password Reset Confirmed'), ('EMAIL_VERIFICATION_SENT', 'Email Verification Sent'), ('EMAIL_VERIFIED', 'Email Verified'), ('EMPLOYEE_CREATED', 'Employee Created'), ('EMPLOYEE_UPDATED', 'Employee Updated'), ('EMPLOYEE_SUSPENDED', 'Employee Suspended'), ('EMPLOYEE_REACTIVATED', 'Employee Reactivated'), ('EMPLOYEE_DELETED', 'Employee Deleted'), ('PIN_RESET', 'PIN Reset'), ('PIN_CHANGED', 'PIN Changed'), ('PIN_ROTATED', 'PIN Rotated'), ('ROLE_CHANGED', 'Role Changed'), ('PERMISSION_OVERRIDE_SET', 'Permission Override Set'), ('ROLE_PERMISSIONS_UPDATED', 'Role Permissions Updated'), ('CASH_SESSION_OPENED', 'Cash Session Opened'), ('CASH_SESSION_CLOSED', 'Cash Session Closed'), ('CASH_SESSION_FORCE_CLOSED', 'Cash Session Force Closed'), ('CASH_MOVEMENT_CREATED', 'Cash Movement Created'), ('OPERATOR_SESSION_STARTED', 'Operator Session Started'), ('OPERATOR_SESSION_ENDED', 'Operator Session Ended'), ('SALE_CREATED_POS', 'Sale Created (POS)'), ('SUBSCRIPTION_CREATED', 'Subscription Created'), ('SUBSCRIPTION_STATUS_CHANGED', 'Subscription Status Changed'), ('SUBSCRIPTION_CANCELED', 'Subscription Canceled'), ('TRIAL_STARTED', 'Trial Started'), ('TRIAL_EXPIRED', 'Trial Expired'), ('SESSION_REVOKED', 'Session Revoked'), ('SESSIONS_REVOKED', 'Sessions Revoked'), ('LOGIN_FAILED', 'Login Failed'), ('ACCESS_DENIED', 'Access Denied'), ('EMAIL_VERIFICATION_BLOCKED', 'Email Verification Blocked'), ('ONBOARDING_SERVICE_SELECTED', 'Onboarding Service Selected'), ('ONBOARDING_CHECKOUT_STARTED', 'Onboarding Checkout Started'), ('ONBOARDING_COMPLETED', 'Onboarding Completed'), ('ACCOUNT_DISABLED', 'Account Disabled'), ('ACCOUNT_ENABLED', 'Account Enabled'), ('PLATFORM_ADMIN_LOGIN', 'Platform Admin Login'), ('PLATFORM_ADMIN_ACTION', 'Platform Admin Generic Action'), ('PLATFORM_STAFF_GRANTED', 'Platform Staff Access Granted'), ('PLATFORM_STAFF_REVOKED', 'Platform Staff Access Revoked'), ('PLATFORM_ROLE_CHANGED', 'Platform Internal Role Changed'), ('ADMIN_LOGIN_SUCCESS', 'Admin Login Success'), ('ADMIN_LOGIN_FAILED', 'Admin Login Failed'), ('ADMIN_LOGIN_THROTTLED', 'Admin Login Throttled'), ('ADMIN_LOGIN_COOLDOWN', 'Admin Login Cooldown Triggered'), ('ADMIN_LOGIN_BLOCKED_IP', 'Admin Login Blocked IP'), ('ADMIN_MFA_REQUIRED', 'Admin MFA Required'), ('ADMIN_MFA_SUCCESS', 'Admin MFA Success'), ('ADMIN_MFA_FAILED', 'Admin MFA Failed'), ('ADMIN_MFA_RECOVERY_USED', 'Admin MFA Recovery Code Used'), ('ADMIN_MFA_ENABLED', 'Admin MFA Enabled'), ('ADMIN_MFA_DISABLED', 'Admin MFA Disabled'), ('ADMIN_MFA_RESET', 'Admin MFA Reset'), ('ADMIN_SUSPICIOUS_AUTH', 'Admin Suspicious Auth Pattern'), ('ADMIN_CLIENT_VIEWED', 'Admin Client Viewed'), ('ADMIN_SUBSCRIPTION_VIEWED', 'Admin Subscription Viewed'), ('ADMIN_NOTE_CREATED', 'Admin Internal Note Created'), ('ADMIN_TICKET_CREATED', 'Admin Ticket Created'), ('ADMIN_TICKET_UPDATED', 'Admin Ticket Updated'), ('ADMIN_TICKET_VIEWED', 'Admin Ticket Viewed'), ('ADMIN_TICKET_MESSAGE', 'Admin Ticket Message Sent'), ('ADMIN_REPORT_VIEWED', 'Admin Report Viewed'), ('ADMIN_ALERTS_VIEWED', 'Admin Alerts Viewed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='True once TOTP enrollment is confirmed.'),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='mfa_recovery_codes',
            field=models.JSONField(blank=True, help_text='List of SHA-256 hashed single-use recovery codes.', null=True),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='mfa_secret_encrypted',
            field=models.TextField(blank=True, help_text='Fernet-encrypted TOTP secret. Never store plaintext.', null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Tenant contact email for this ticket (pre-filled from business owner)', max_length=254),
        ),
    ]
