# Generated by Django 5.0.14 on 2026-03-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_blog_phase5_audit_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager / Encargado'), ('cashier', 'Cashier / Caja'), ('staff', 'Staff / Empleado'), ('viewer', 'Solo lectura'), ('kitchen', 'Cocina'), ('salon', 'Salon / Toma pedidos'), ('analyst', 'Analyst'), ('contador', 'Contador')], default='owner', max_length=24),
        ),
        migrations.AlterField(
            model_name='rolepermissionoverride',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager / Encargado'), ('cashier', 'Cashier / Caja'), ('staff', 'Staff / Empleado'), ('viewer', 'Solo lectura'), ('kitchen', 'Cocina'), ('salon', 'Salon / Toma pedidos'), ('analyst', 'Analyst'), ('contador', 'Contador')], help_text='Role to configure (e.g., manager, cashier)', max_length=24),
        ),
    ]
