# Generated by Django 5.0.14 on 2026-05-11 05:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_accountprofile_auth_provider_google_sub'),
        ('business', '0024_remove_businessonboardingprogress_uq_onboarding_progress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notif_type', models.CharField(choices=[('support_ticket_created', 'Ticket de soporte creado'), ('support_ticket_replied', 'Respuesta en ticket de soporte'), ('support_ticket_escalated', 'Ticket escalado'), ('support_ticket_overdue', 'Ticket sin respuesta (vencido)'), ('billing_payment_failed', 'Pago fallido'), ('billing_trial_ending', 'Trial por vencer'), ('billing_subscription_canceled', 'Suscripción cancelada'), ('billing_subscription_created', 'Nueva suscripción'), ('review_reported', 'Reseña reportada'), ('review_response_pending', 'Reseña sin respuesta'), ('security_admin_login_failed', 'Login de admin fallido'), ('security_mfa_disabled', 'MFA deshabilitado'), ('security_suspicious_auth', 'Auth sospechoso'), ('security_multiple_failures', 'Múltiples fallos de auth'), ('system_error', 'Error del sistema'), ('system_info', 'Información del sistema')], help_text='Category of the notification.', max_length=48)),
                ('severity', models.CharField(choices=[('info', 'Informativo'), ('success', 'Exitoso'), ('warning', 'Advertencia'), ('critical', 'Crítico')], default='info', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('unread', 'No leída'), ('read', 'Leída'), ('resolved', 'Resuelta'), ('archived', 'Archivada')], db_index=True, default='unread', max_length=16)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('target_role', models.CharField(blank=True, default='', max_length=24)),
                ('related_object_type', models.CharField(blank=True, default='', max_length=64)),
                ('related_object_id', models.CharField(blank=True, default='', max_length=64)),
                ('action_url', models.CharField(blank=True, default='', help_text='Optional URL for the CTA button in the notification item.', max_length=500)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, default='', help_text='Optional dedup key (SHA-256[:64] of notif_type:related_object_type:related_object_id). Used by create_admin_notification() to skip duplicate creation within a time window.', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context. Sensitive keys are stripped before saving.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, help_text='The business this notification is about, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notifications', to='business.business')),
                ('target_user', models.ForeignKey(blank=True, help_text='If set, only this staff user should see the notification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notifications_targeted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='adminnotif_status_ts_idx'), models.Index(fields=['target_role', '-created_at'], name='adminnotif_role_ts_idx'), models.Index(fields=['business', '-created_at'], name='adminnotif_business_ts_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='adminnotif_related_idx')],
            },
        ),
    ]
