# Generated by Django 5.0.14 on 2026-05-09 19:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0024_remove_businessonboardingprogress_uq_onboarding_progress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(db_index=True, max_length=254)),
                ('from_email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('template_key', models.CharField(db_index=True, max_length=100)),
                ('html_body', models.TextField(blank=True)),
                ('text_body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('complained', 'Complained')], db_index=True, default='queued', max_length=20)),
                ('provider', models.CharField(choices=[('amazon_ses', 'Amazon SES'), ('django', 'Django Email Backend')], db_index=True, default='django', max_length=30)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_deliveries', to='business.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='notificatio_status_4cbb98_idx'), models.Index(fields=['business', 'created_at'], name='notificatio_busines_76593d_idx'), models.Index(fields=['template_key', 'created_at'], name='notificatio_templat_1d12fe_idx')],
            },
        ),
    ]
