# Generated by Django 5.0.14 on 2026-01-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_busines_1a89b8_idx',
            old_name='orders_order_busines_3cc800_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_busines_8b78fd_idx',
            old_name='orders_order_busines_f0f493_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_order_i_5d347b_idx',
            old_name='orders_orderi_order_id_9a3d5b_idx',
        ),
    ]
