# Generated by Django 5.0.14 on 2026-01-19 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_cash_session'),
        ('orders', '0002_rename_orders_order_busines_3cc800_idx_orders_orde_busines_1a89b8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='sales.sale'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pendiente'),
                    ('preparing', 'En preparación'),
                    ('ready', 'Lista'),
                    ('delivered', 'Entregada'),
                    ('charged', 'Cobrada'),
                    ('canceled', 'Cancelada'),
                ],
                default='pending',
                max_length=24,
            ),
        ),
    ]
