# Generated by Django 5.0.14 on 2026-01-24 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_commercialsettings_options'),
        ('orders', '0003_order_sale_and_status_choices'),
        ('resto', '__first__'),
        ('sales', '0004_sale_cash_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='resto.table'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['business', 'table'], name='orders_orde_busines_4d9609_idx'),
        ),
    ]
