# Generated by Django 5.0.14 on 2026-01-24

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_commercialsettings_options'),
        ('orders', '0004_order_table_order_orders_orde_busines_4d9609_idx'),
        ('resto', '__first__'),
        ('menu', '__first__'),
        ('catalog', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('dine_in', 'Salón'), ('pickup', 'Retiro'), ('delivery', 'Delivery')], default='dine_in', max_length=24)),
                ('table_name', models.CharField(blank=True, max_length=64)),
                ('customer_name', models.CharField(blank=True, max_length=128)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('editing', 'En edición'), ('submitted', 'Confirmado')], default='editing', max_length=24)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('items_count', models.PositiveIntegerField(default=0)),
                ('client_reference', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(default='pos', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_drafts', to='business.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_drafts_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft', to='orders.order')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='resto.table')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_drafts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDraftItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_status', models.CharField(choices=[('in', 'Stock OK'), ('low', 'Stock bajo'), ('critical', 'Crítico'), ('out', 'Sin stock')], default='in', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orderdraft')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_draft_items', to='menu.menuitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_draft_items', to='catalog.product')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='orderdraft',
            index=models.Index(fields=['business', 'status'], name='orders_draf_busines_1a2bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdraft',
            index=models.Index(fields=['business', 'client_reference'], name='orders_draf_busines_a1b2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdraftitem',
            index=models.Index(fields=['draft'], name='orders_draf_draft_12ab34_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdraftitem',
            index=models.Index(fields=['draft', 'menu_item'], name='orders_draf_draft_56cd78_idx'),
        ),
    ]
