# Generated by Django 5.0.14 on 2026-01-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderdraft'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderdraft',
            new_name='orders_orde_busines_9b2f40_idx',
            old_name='orders_draf_busines_1a2bc8_idx',
        ),
        migrations.RenameIndex(
            model_name='orderdraft',
            new_name='orders_orde_busines_54ec7b_idx',
            old_name='orders_draf_busines_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='orderdraftitem',
            new_name='orders_orde_draft_i_421729_idx',
            old_name='orders_draf_draft_12ab34_idx',
        ),
        migrations.RenameIndex(
            model_name='orderdraftitem',
            new_name='orders_orde_draft_i_03e891_idx',
            old_name='orders_draf_draft_56cd78_idx',
        ),
    ]
