# Generated by Django 5.0.14 on 2026-02-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0008_orderitem_sold_without_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='kitchen_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='kitchen_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='kitchen_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='kitchen_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En preparación'), ('ready', 'Listo'), ('done', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='last_kitchen_update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['kitchen_status'], name='orders_orde_kitchen_733d43_idx'),
        ),
    ]
