# Generated by Django 5.0.14 on 2026-02-12 00:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_business_default_service_and_more'),
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='opening_balance_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='FixedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del gasto fijo (ej: Internet, Alquiler)', max_length=255)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=4, help_text='Monto por defecto opcional', max_digits=19, null=True)),
                ('due_day', models.PositiveSmallIntegerField(blank=True, help_text='Día del mes de vencimiento (1-28)', null=True)),
                ('frequency', models.CharField(choices=[('monthly', 'Mensual')], default='monthly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_expenses', to='business.business')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FixedExpensePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='Primer día del mes (YYYY-MM-01)')),
                ('amount', models.DecimalField(decimal_places=4, help_text='Monto para este periodo', max_digits=19)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('skipped', 'Omitido')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixed_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='treasury.fixedexpense')),
                ('paid_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_fixed_expense_periods', to='treasury.account')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_expense_period_payments', to='treasury.transaction')),
            ],
            options={
                'ordering': ['-period'],
                'unique_together': {('fixed_expense', 'period')},
            },
        ),
    ]
