# Generated by Django 5.0.14 on 2026-02-24 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0003_treasury_finance_full_upgrade'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='treasury_exp_status_due_idx',
        ),
        migrations.RemoveIndex(
            model_name='fixedexpenseperiod',
            name='treasury_fep_fe_period_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='treasury_txn_biz_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='treasury_txn_dir_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='treasury_txn_acct_date_idx',
        ),
    ]
