# Generated by Django 5.0.14 on 2026-03-25 05:04

import apps.treasury.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_expense_document'),
        ('treasury', '0006_payment_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensetemplate',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ExpenseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.treasury.models.expense_document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('document_kind', models.CharField(choices=[('invoice', 'Factura'), ('receipt', 'Recibo'), ('ticket', 'Ticket'), ('contract', 'Contrato'), ('other', 'Otro')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Subido'), ('archived', 'Archivado'), ('queued', 'En cola'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('failed', 'Fallido')], default='uploaded', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_documents', to='business.business')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='treasury.expense')),
                ('fixed_expense_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='treasury.fixedexpenseperiod')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_expense_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='expdoc_biz_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='expensedocument',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('expense__isnull', False), ('fixed_expense_period__isnull', True)), models.Q(('expense__isnull', True), ('fixed_expense_period__isnull', False)), _connector='OR'), name='expdoc_exactly_one_origin'),
        ),
    ]
