# Generated by Django 5.0.14 on 2026-03-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0007_expense_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensedocument',
            name='extraction_source',
            field=models.CharField(blank=True, choices=[('qr', 'QR'), ('ocr', 'OCR'), ('mixed', 'QR + OCR'), ('none', 'Sin extracción')], help_text='Fuente de extracción usada (qr, ocr, mixed, none).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='expensedocument',
            name='normalized_data',
            field=models.JSONField(blank=True, help_text='Datos normalizados: issuer_name, issuer_tax_id, total_amount, etc.', null=True),
        ),
        migrations.AddField(
            model_name='expensedocument',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp de finalización del procesamiento.', null=True),
        ),
        migrations.AddField(
            model_name='expensedocument',
            name='processing_errors',
            field=models.JSONField(blank=True, help_text='Lista de errores/advertencias del pipeline de procesamiento.', null=True),
        ),
        migrations.AddField(
            model_name='expensedocument',
            name='raw_extraction',
            field=models.JSONField(blank=True, help_text='Resultado crudo de la extracción (QR payload, OCR text, etc.)', null=True),
        ),
        migrations.AlterModelTable(
            name='expensetemplate',
            table='treasury_expensetemplate',
        ),
    ]
