# Generated by Django 5.0.14 on 2026-02-24 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockmovement_unit_cost_replenishment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='inventory_s_busines_605beb_idx',
            old_name='inventory_s_busines_rep_idx',
        ),
        migrations.RenameIndex(
            model_name='stockreplenishment',
            new_name='inventory_s_busines_20f1f2_idx',
            old_name='inventory_r_busines_occ_idx',
        ),
        migrations.RenameIndex(
            model_name='stockreplenishment',
            new_name='inventory_s_busines_639547_idx',
            old_name='inventory_r_busines_sts_idx',
        ),
    ]
