# Generated by Django 5.0.14 on 2026-03-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockreplenishment_occurred_at_datefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
