# Generated by Django 5.0.14 on 2026-01-31 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0004_alter_commercialsettings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('operation', 'Operation'), ('admin', 'Admin'), ('insights', 'Insights')], max_length=32)),
                ('vertical', models.CharField(choices=[('commercial', 'Commercial'), ('restaurant', 'Restaurant'), ('both', 'Both')], max_length=32)),
                ('price_monthly', models.IntegerField(help_text='Price in cents')),
                ('price_yearly', models.IntegerField(blank=True, help_text='Price in cents', null=True)),
                ('is_core', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('requires', models.ManyToManyField(blank=True, to='billing.module')),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('vertical', models.CharField(choices=[('commercial', 'Commercial'), ('restaurant', 'Restaurant')], max_length=32)),
                ('badge', models.CharField(blank=True, max_length=64, null=True)),
                ('pricing_mode', models.CharField(choices=[('fixed_price', 'Fixed Price'), ('discount_percent', 'Discount Percent')], max_length=32)),
                ('fixed_price_monthly', models.IntegerField(blank=True, help_text='Override price in cents', null=True)),
                ('fixed_price_yearly', models.IntegerField(blank=True, help_text='Override price in cents', null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_default_recommended', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('modules', models.ManyToManyField(related_name='bundles', to='billing.module')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('applies_to', models.CharField(choices=[('bundle', 'Bundle'), ('module', 'Module')], max_length=32)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fixed_override_price', models.IntegerField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.bundle')),
                ('target_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.module')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('bundle', 'Bundle'), ('custom', 'Custom')], max_length=32)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=32)),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('price_snapshot', models.JSONField(default=dict, help_text='Snapshot of pricing at the time of subscription')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('past_due', 'Past Due'), ('canceled', 'Canceled')], default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.bundle')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_subscription', to='business.business')),
                ('selected_modules', models.ManyToManyField(blank=True, to='billing.module')),
            ],
        ),
    ]
