# Generated by Django 5.0.14 on 2026-02-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_paymentevent_plan_subscription_current_period_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='vertical',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('restaurant', 'Restaurant'), ('menu_qr', 'Menu QR')], max_length=32),
        ),
        migrations.AlterField(
            model_name='module',
            name='vertical',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('restaurant', 'Restaurant'), ('both', 'Both'), ('menu_qr', 'Menu QR')], max_length=32),
        ),
    ]
