# Generated by Django 5.0.14 on 2026-02-22 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_bundle_vertical_alter_module_vertical'),
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSubscriptionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_plan_code', models.CharField(max_length=32)),
                ('billing_cycle', models.CharField(max_length=16)),
                ('config_snapshot', models.JSONField(default=dict, help_text='Full configuration: crm, invoicing, branches_extra_qty, seats_extra_qty')),
                ('line_items', models.JSONField(default=list, help_text='List of line items with description, quantity, unit_price, total')),
                ('total_amount', models.IntegerField(help_text='Total amount in centavos')),
                ('requires_checkout', models.BooleanField(default=False)),
                ('mp_preference_id', models.CharField(blank=True, max_length=128, null=True)),
                ('mp_init_point', models.URLField(blank=True, max_length=500, null=True)),
                ('mp_payment_id', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending_payment', max_length=32)),
                ('is_upgrade', models.BooleanField(default=False)),
                ('is_downgrade', models.BooleanField(default=False)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='When to apply the change (downgrades)', null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_subscription_changes', to='business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
