# Generated by Django 5.0.14 on 2026-03-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_fix_checkout_session_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingevent',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Stack trace or description if status=ERROR.'),
        ),
        migrations.AlterField(
            model_name='billingevent',
            name='payload',
            field=models.JSONField(help_text='Raw provider payload. Never modified.'),
        ),
        migrations.AlterField(
            model_name='billingevent',
            name='provider_event_id',
            field=models.CharField(help_text='Idempotency key. Unique per provider. e.g. MP notification ID.', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='billingevent',
            name='received_at',
            field=models.DateTimeField(help_text='Timestamp when the event was received.'),
        ),
        migrations.AlterField(
            model_name='mpcheckoutsession',
            name='idempotency_key',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='attempt_at',
            field=models.DateTimeField(help_text='When this payment attempt was initiated.'),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='external_payment_id',
            field=models.CharField(blank=True, help_text='Provider payment ID. Sparse unique (NULL allowed for pending attempts).', max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='failure_reason',
            field=models.CharField(blank=True, help_text='Rejection code or description from provider.', max_length=256),
        ),
        migrations.AlterField(
            model_name='subscriptionv2',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='If True, subscription will not renew at period end.'),
        ),
        migrations.AlterField(
            model_name='subscriptionv2',
            name='plan_code',
            field=models.CharField(help_text='e.g. gestion_pro_monthly', max_length=64),
        ),
    ]
