# Generated by Django 5.0.14 on 2026-04-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_subscriptionv2_cancel_requested_at_and_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='vertical',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('restaurant', 'Restaurant'), ('menu_qr', 'Menu QR'), ('qr_reviews', 'QR de Reseñas')], max_length=32),
        ),
        migrations.AlterField(
            model_name='module',
            name='vertical',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('restaurant', 'Restaurant'), ('both', 'Both'), ('menu_qr', 'Menu QR'), ('qr_reviews', 'QR de Reseñas')], max_length=32),
        ),
        migrations.AlterField(
            model_name='subscriptionv2',
            name='service_type',
            field=models.CharField(choices=[('gestion', 'Gestión Comercial'), ('restaurante', 'Restaurantes'), ('menu_qr', 'Menú QR'), ('menu_qr_visual', 'Menú QR Visual'), ('menu_qr_marca', 'Menú QR Marca'), ('qr_reviews', 'QR de Reseñas')], max_length=32),
        ),
    ]
