# Generated by Django 5.0.14 on 2026-08-05 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_subscriptionv2_canceled_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionv2',
            name='manual_grant_reason',
            field=models.CharField(blank=True, help_text='Internal reason recorded by the admin who granted complimentary access.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionv2',
            name='manual_granted_by',
            field=models.ForeignKey(blank=True, help_text='Platform admin who granted this complimentary access (provider=manual only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_granted_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
