# Generated by ChatGPT on 2026-01-19
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    ('business', '0001_initial'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ('sales', '0001_initial'),
  ]

  operations = [
    migrations.CreateModel(
      name='InvoiceSeries',
      fields=[
        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('code', models.CharField(default='X', max_length=8)),
        ('prefix', models.CharField(blank=True, max_length=16)),
        ('next_number', models.PositiveIntegerField(default=1)),
        ('is_active', models.BooleanField(default=True)),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_series', to='business.business')),
      ],
      options={
        'ordering': ['code'],
      },
    ),
    migrations.CreateModel(
      name='Invoice',
      fields=[
        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('number', models.PositiveIntegerField()),
        ('full_number', models.CharField(max_length=48)),
        ('status', models.CharField(choices=[('issued', 'Emitida'), ('voided', 'Anulada')], default='issued', max_length=16)),
        ('issued_at', models.DateTimeField()),
        ('customer_name', models.CharField(blank=True, max_length=255)),
        ('customer_tax_id', models.CharField(blank=True, max_length=64)),
        ('customer_address', models.CharField(blank=True, max_length=255)),
        ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='business.business')),
        ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
        ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='sales.sale')),
        ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoices.invoiceseries')),
      ],
      options={
        'ordering': ['-issued_at', '-number'],
      },
    ),
    migrations.AddConstraint(
      model_name='invoice',
      constraint=models.UniqueConstraint(fields=('business', 'series', 'number'), name='invoice_unique_number_per_series'),
    ),
    migrations.AddConstraint(
      model_name='invoiceseries',
      constraint=models.UniqueConstraint(fields=('business', 'code'), name='invoice_series_unique_code_per_business'),
    ),
    migrations.AddIndex(
      model_name='invoice',
      index=models.Index(fields=['business', 'issued_at'], name='invoices_invoice_busines_2b3f52_idx'),
    ),
    migrations.AddIndex(
      model_name='invoice',
      index=models.Index(fields=['business', 'status'], name='invoices_invoice_busines_909183_idx'),
    ),
  ]
