# Generated by Django 5.0.14 on 2026-01-19 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_in_busines_b10fdc_idx',
            old_name='invoices_invoice_busines_2b3f52_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_in_busines_94d607_idx',
            old_name='invoices_invoice_busines_909183_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
