# Generated by Django 5.0.14 on 2026-02-17 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_alter_businessbillingprofile_options_and_more'),
        ('invoices', '0004_migrate_series_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentseries',
            options={'ordering': ['document_type', 'letter']},
        ),
        migrations.RemoveConstraint(
            model_name='documentseries',
            name='unique_business_doc_type_letter_pv',
        ),
        migrations.RemoveIndex(
            model_name='documentseries',
            name='doc_series_business_type_default_idx',
        ),
        migrations.AlterField(
            model_name='documentseries',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_by_branch', to='business.business'),
        ),
        migrations.AlterField(
            model_name='documentseries',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Factura'), ('quote', 'Presupuesto'), ('receipt', 'Recibo'), ('credit_note', 'Nota de Crédito'), ('debit_note', 'Nota de Débito'), ('delivery_note', 'Remito')], max_length=32),
        ),
        migrations.AlterField(
            model_name='documentseries',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='documentseries',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentseries',
            name='letter',
            field=models.CharField(default='X', max_length=8),
        ),
        migrations.AlterField(
            model_name='documentseries',
            name='next_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='documentseries',
            name='point_of_sale',
            field=models.CharField(blank=True, help_text='Punto de venta (ej: 0001)', max_length=8),
        ),
        migrations.AlterField(
            model_name='documentseries',
            name='prefix',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='documentseries',
            name='suffix',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddIndex(
            model_name='documentseries',
            index=models.Index(fields=['business', 'document_type', 'is_active'], name='document_se_busines_7bb327_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentseries',
            constraint=models.UniqueConstraint(fields=('business', 'document_type', 'letter', 'point_of_sale'), name='unique_series_per_doc_type'),
        ),
    ]
